#!/usr/bin/env bash
# Smoke-test the standup endpoints.
#
#   bash test-standup.sh                       # against localhost:2122
#   bash test-standup.sh https://restart.prayas.space   # through the tunnel
#   bash test-standup.sh http://127.0.0.1:2122 --push   # also fire the ntfy pushes
#
# Entries it creates are deleted again, and the weekly cache is rebuilt at the
# end, so it is safe to run against the live log.

set -u

BASE="${1:-http://127.0.0.1:2122}"
BASE="${BASE%/}"
PUSH=0
for arg in "$@"; do [ "$arg" = "--push" ] && PUSH=1; done

ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"
TOKEN="${WEBHOOK_TOKEN:-}"
if [ -z "$TOKEN" ] && [ -f "$ENV_FILE" ]; then
    TOKEN=$(sed -n 's/^WEBHOOK_TOKEN=//p' "$ENV_FILE" | head -1 | tr -d '"'"'"'')
fi
if [ -z "$TOKEN" ]; then
    echo "No WEBHOOK_TOKEN — set it in $ENV_FILE or export it." >&2
    exit 1
fi

MARK="smoketest-$$"
pass=0; fail=0
ok()  { printf '  \033[32mPASS\033[0m  %s\n' "$1"; pass=$((pass + 1)); }
bad() { printf '  \033[31mFAIL\033[0m  %s\n' "$1"; fail=$((fail + 1)); }

# code <desc> <expected> <url> [method]
code() {
    local got
    got=$(curl -s -o /dev/null -w '%{http_code}' -X "${4:-GET}" --max-time 20 "$3")
    if [ "$got" = "$2" ]; then ok "$1"; else bad "$1 (got $got, wanted $2)"; fi
}

# body <desc> <needle> <url>
body() {
    if curl -s --max-time 30 "$3" | grep -qF "$2"; then ok "$1"; else bad "$1 (no '$2')"; fi
}

echo "standup smoke test -> $BASE"
echo

echo "auth gate"
code "no token is rejected"    401 "$BASE/standup"
code "bad token is rejected"   401 "$BASE/standup?token=nope"
code "good token is accepted"  200 "$BASE/standup?token=$TOKEN"
body "page is the log UI"      "STANDUP LOG" "$BASE/standup?token=$TOKEN"

echo
echo "logging"
IDS=""
for pair in "progress|$MARK shipped the deck agent" \
            "ai|$MARK groq drafted the weekly update" \
            "gap|$MARK still tagging notes by hand"; do
    tag="${pair%%|*}"; txt="${pair#*|}"
    resp=$(curl -s --max-time 20 -X POST "$BASE/standup/log?token=$TOKEN" \
        -H 'Content-Type: application/json' -d "{\"text\":\"$txt\",\"tag\":\"$tag\"}")
    id=$(printf '%s' "$resp" | python3 -c \
        'import sys,json; print(json.load(sys.stdin).get("entry",{}).get("id",""))' 2>/dev/null)
    if [ -n "$id" ]; then ok "logged [$tag] -> $id"; IDS="$IDS $id"; else bad "log [$tag]: $resp"; fi
done

body "entries come back"  "$MARK shipped the deck agent" "$BASE/standup/entries?token=$TOKEN"
body "tag was preserved"  '"tag":"gap"'                  "$BASE/standup/entries?token=$TOKEN"

echo
echo "input validation"
empty=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 \
    -X POST "$BASE/standup/log?token=$TOKEN" \
    -H 'Content-Type: application/json' -d '{"text":"   "}')
[ "$empty" = "400" ] && ok "blank text rejected" || bad "blank text (got $empty, wanted 400)"

nof=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 \
    -X POST "$BASE/standup/delete?token=$TOKEN" \
    -H 'Content-Type: application/json' -d '{"id":"nosuchid"}')
[ "$nof" = "404" ] && ok "unknown id rejected" || bad "unknown id (got $nof, wanted 404)"

echo
echo "weekly draft  (regenerates — one model call)"
draft=$(curl -s --max-time 60 "$BASE/standup/weekly?token=$TOKEN&refresh=1")
for section in "1. The Progress" "2. The AI Edge" "3. The Automation Gap" \
               "4. Values in Action" "5. The Horizon"; do
    printf '%s' "$draft" | grep -qF "$section" \
        && ok "section: $section" || bad "section missing: $section"
done
source=$(printf '%s' "$draft" | python3 -c \
    'import sys,json; print(json.load(sys.stdin).get("generated_by","?"))' 2>/dev/null)
if [ "$source" = "template" ]; then
    echo "  ....  generated by: template  (no GROQ_API_KEY, or the model call failed"
    echo "        — check the webhook log for the reason)"
else
    ok "generated by: $source"
fi

if [ "$PUSH" = "1" ]; then
    echo
    echo "notifications  (your phone should buzz twice)"
    body "daily nudge sent"  '"status":"ok"' "$BASE/standup/nudge?token=$TOKEN"
    body "friday push sent"  '"text"'        "$BASE/standup/friday?token=$TOKEN"
else
    echo
    echo "notifications  (skipped — pass --push to fire them)"
fi

echo
echo "cleanup"
for id in $IDS; do
    got=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 \
        -X POST "$BASE/standup/delete?token=$TOKEN" \
        -H 'Content-Type: application/json' -d "{\"id\":\"$id\"}")
    [ "$got" = "200" ] && ok "removed $id" || bad "remove $id (got $got)"
done
if curl -s --max-time 30 "$BASE/standup/entries?token=$TOKEN" | grep -qF "$MARK"; then
    bad "test entries still present — remove them by hand"
else
    ok "test entries removed"
fi
# The draft above was cached with the test entries in it; rebuild it clean.
curl -s -o /dev/null --max-time 60 "$BASE/standup/weekly?token=$TOKEN&refresh=1"
ok "weekly cache rebuilt without test data"

echo
echo "-----------------------------------------"
printf 'passed %d, failed %d\n' "$pass" "$fail"
[ "$fail" -eq 0 ] || exit 1
